### ISSUE TITLE
人民币大写角的叫法有误

### ISSUE THREAD

**Issue by season886** [wilon/php-number2chinese#4]
646743393.06
陆亿肆仟陆佰柒拾肆万叁仟叁佰玖拾叁元零角陆分
应该是
陆亿肆仟陆佰柒拾肆万叁仟叁佰玖拾叁元零陆分

**Comment by wilon** [comment]
有待商榷。不是有误，而是个人读法不同吧。

**Comment by wilon** [comment]
查了些资料，http://bbs.chinaacc.com/forum-2-35/topic-1181907.html ，确实有误。感谢
